<?php

/**
 * Channel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    reader
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Channel extends BaseChannel
{
	public function getItemsChunk($block = 0)
	{
		return Doctrine::getTable('Item')
			->createQuery()
			->where('channel_id = ?', $this->id)
			->limit(10)
			->offset($block * 10)
			->orderBy('pubdate DESC, id DESC')
			->execute();
	}
}
