<?php

/**
 * ChannelCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChannelCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChannelCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChannelCategory');
    }
}